import { and, asc, desc, eq, ilike, inArray, or, sql, sum, count as drizzleCount } from 'drizzle-orm';
import { db } from '../db';
import {
  modernEstimates,
  estimateLineItems,
  estimateTemplates,
  type ModernEstimate,
  type EstimateLineItem,
  type EstimateTemplate,
  type InsertModernEstimate,
  type InsertEstimateLineItem,
  type InsertEstimateTemplate,
} from '../../shared/schema';
import { NotFoundError, BadRequestError } from '../utils/error-handler';
// New enums / helper types (flexible filtering, versioning, etc.)
import {
  EstimateSourceEnum,
  PaymentTermsEnum,
  SignatureMethodEnum,
  VersionReasonEnum,
  type EstimateSourceEnumType,
  type PaymentTermsEnumType,
  type SignatureMethodEnumType,
  type VersionReasonEnumType,
} from '../../shared/estimates-schema';

// Narrow helper to coerce arrays / single values into array – used for filters
const toArray = <T>(val?: T | T[]): T[] | undefined =>
  val === undefined ? undefined : Array.isArray(val) ? val : [val];

export class EstimateRepository {
  // --- Modern Estimates ---

  async createEstimate(data: Omit<InsertModernEstimate, 'id' | 'createdAt' | 'updatedAt' | 'estimateNumber'>): Promise<ModernEstimate> {
    const [estimate] = await db
      .insert(modernEstimates)
      .values({
        ...data,
        // estimateNumber is auto-generated by DB default using SQL function
      })
      .returning();
    if (!estimate) {
      throw new Error('Failed to create estimate'); // Should not happen if DB is responsive
    }
    return estimate;
  }

  async updateEstimate(id: string, data: Partial<Omit<InsertModernEstimate, 'id' | 'createdAt' | 'updatedAt' | 'estimateNumber'>>): Promise<ModernEstimate> {
    const [updatedEstimate] = await db
      .update(modernEstimates)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(modernEstimates.id, id))
      .returning();

    if (!updatedEstimate) {
      throw new NotFoundError(`Estimate with ID ${id} not found for update.`);
    }
    return updatedEstimate;
  }

  /**
   * Convenience helper to create an estimate directly from a lead record.
   * Fields such as customer info, service type, source, etc. are pre-filled.
   * @param leadData – The subset of lead fields required for an estimate.
   * @param override  – Allow UI to override defaults (e.g., title).
   */
  async createEstimateFromLead(
    leadData: {
      leadId: string;
      customerId?: number | null;
      title?: string;
      serviceType?: string | null;
      source?: EstimateSourceEnumType;
      notes?: string | null;
      createdBy?: string;
    },
    override: Partial<Omit<InsertModernEstimate, 'id' | 'createdAt' | 'updatedAt' | 'estimateNumber'>> = {},
  ): Promise<ModernEstimate> {
    const insertPayload: Omit<InsertModernEstimate, 'id' | 'createdAt' | 'updatedAt' | 'estimateNumber'> = {
      title: leadData.title ?? `Estimate for Lead`,
      leadId: leadData.leadId,
      customerId: leadData.customerId ?? null,
      estimateType: 'detailed',
      status: 'draft',
      source: leadData.source ?? 'lead',
      notes: leadData.notes ?? null,
      createdBy: leadData.createdBy,
      subtotal: '0.00',
      taxRate: '0.0000',
      total: '0.00',
      ...override,
    };
    return this.createEstimate(insertPayload);
  }

  /**
   * Create a new version of an estimate, copying line items and linking
   * via `versionOf`.  The original estimate's status is set to `superseded`.
   */
  async createEstimateVersion(
    origId: string,
    reason: VersionReasonEnumType,
    createdBy: string,
  ): Promise<ModernEstimate> {
    // 1. Fetch original
    const orig = await this.getEstimateById(origId);
    if (!orig) throw new NotFoundError(`Original estimate ${origId} not found`);

    // 2. Insert copy (omit id/number)
    const { id: _, estimateNumber: __, createdAt: ___, updatedAt: ____, ...clone } = orig;
    const newEstimate = await this.createEstimate({
      ...clone,
      versionOf: origId,
      status: 'revision',
      versionReason: reason,
      createdBy,
    } as any);

    // 3. Copy line-items
    if (orig.lineItems?.length) {
      const newItems: InsertEstimateLineItem[] = orig.lineItems.map((li) => ({
        ...li,
        id: undefined as never,
        estimateId: newEstimate.id,
      }));
      await this.bulkCreateLineItems(newItems);
    }

    // 4. Mark original as superseded
    await this.updateEstimateStatus(origId, 'superseded');

    return newEstimate;
  }

  /** Returns all versions (including original) ordered by createdAt ASC */
  async getEstimateVersions(id: string): Promise<ModernEstimate[]> {
    // Determine root id (either self or versionOf)
    const est = await this.getEstimateById(id);
    if (!est) throw new NotFoundError('Estimate not found');
    const rootId = est.versionOf ?? est.id;
    return db
      .select()
      .from(modernEstimates)
      .where(or(eq(modernEstimates.id, rootId), eq(modernEstimates.versionOf, rootId)))
      .orderBy(asc(modernEstimates.createdAt));
  }

  /** Simple helper to compute deposit based on percent or fixed */
  calculateDeposit(total: number, percent?: number, fixed?: number): number {
    if (percent && percent > 0) {
      return Number(((total * percent) / 100).toFixed(2));
    }
    if (fixed && fixed > 0) return fixed;
    return 0;
  }

  /**
   * Approve / Decline workflow including signature metadata.
   */
  async updateEstimateApproval(
    id: string,
    status: 'approved' | 'declined',
    options: {
      signatureMethod?: SignatureMethodEnumType;
      signatureDataUrl?: string | null;
      approvedBy?: string | null;
      declinedReason?: string | null;
    },
  ): Promise<ModernEstimate> {
    const now = new Date();
    const updateData: Partial<ModernEstimate> = {
      status,
      signature: options.signatureDataUrl ?? undefined,
      signatureMethod: options.signatureMethod ?? undefined,
      approvedAt: status === 'approved' ? now : undefined,
      declinedAt: status === 'declined' ? now : undefined,
    };
    return this.updateEstimate(id, updateData as any);
  }
  async getEstimateById(id: string): Promise<(ModernEstimate & { lineItems: EstimateLineItem[] }) | undefined> {
    const result = await db.query.modernEstimates.findFirst({
      where: eq(modernEstimates.id, id),
      with: {
        lineItems: {
          orderBy: [asc(estimateLineItems.sortOrder)],
        },
      },
    });
    return result as (ModernEstimate & { lineItems: EstimateLineItem[] }) | undefined;
  }

  async getEstimates(params: {
    page?: number;
    limit?: number;
    search?: string;
    status?: string | string[];
    leadId?: string;
    customerId?: number;
    jobId?: number;
    dateFrom?: string;
    dateTo?: string;
    source?: EstimateSourceEnumType | EstimateSourceEnumType[];
    sortBy?: keyof ModernEstimate;
    sortDirection?: 'asc' | 'desc';
  }): Promise<{ data: ModernEstimate[]; pagination: { total: number; page: number; limit: number; pages: number } }> {
    const {
      page = 1,
      limit = 50,
      search,
      status,
      leadId,
      customerId,
      jobId,
      dateFrom,
      dateTo,
      source,
      sortBy = 'createdAt',
      sortDirection = 'desc',
    } = params;

    const offset = (page - 1) * limit;
    const conditions = [];

    if (search) {
      conditions.push(
        or(
          ilike(modernEstimates.title, `%${search}%`),
          ilike(modernEstimates.estimateNumber, `%${search}%`),
          ilike(modernEstimates.notes, `%${search}%`)
        )
      );
    }
    if (status) {
      if (Array.isArray(status)) {
        conditions.push(inArray(modernEstimates.status, status));
      } else {
        conditions.push(eq(modernEstimates.status, status));
      }
    }
    if (leadId) conditions.push(eq(modernEstimates.leadId, leadId));
    if (customerId) conditions.push(eq(modernEstimates.customerId, customerId));
    if (jobId) conditions.push(eq(modernEstimates.jobId, jobId));
    if (dateFrom) conditions.push(sql`${modernEstimates.createdAt} >= ${dateFrom}`);
    if (dateTo) conditions.push(sql`${modernEstimates.createdAt} <= ${dateTo}`);
    if (source) {
      const arr = toArray(source);
      if (arr) {
        conditions.push(inArray(modernEstimates.source, arr));
      }
    }

    const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

    const dataQuery = db
      .select()
      .from(modernEstimates)
      .where(whereClause)
      .orderBy(sortDirection === 'asc' ? asc(modernEstimates[sortBy]) : desc(modernEstimates[sortBy]))
      .limit(limit)
      .offset(offset);

    const countQuery = db
      .select({ total: drizzleCount(modernEstimates.id) })
      .from(modernEstimates)
      .where(whereClause);

    const [data, totalResult] = await Promise.all([dataQuery, countQuery]);
    const total = totalResult[0].total;

    return {
      data,
      pagination: {
        total,
        page,
        limit,
        pages: Math.ceil(total / limit),
      },
    };
  }

  async deleteEstimate(id: string): Promise<ModernEstimate | undefined> {
    const [deletedEstimate] = await db.delete(modernEstimates).where(eq(modernEstimates.id, id)).returning();
    // Line items should be deleted by cascade if set up in DB schema
    return deletedEstimate;
  }
  
  async updateEstimateStatus(id: string, status: string): Promise<ModernEstimate> {
    const [updatedEstimate] = await db
      .update(modernEstimates)
      .set({ status, updatedAt: new Date() })
      .where(eq(modernEstimates.id, id))
      .returning();
    if (!updatedEstimate) {
      throw new NotFoundError(`Estimate with ID ${id} not found for status update.`);
    }
    return updatedEstimate;
  }

  // --- Estimate Line Items ---

  async getLineItemsByEstimateId(estimateId: string): Promise<EstimateLineItem[]> {
    return db
      .select()
      .from(estimateLineItems)
      .where(eq(estimateLineItems.estimateId, estimateId))
      .orderBy(asc(estimateLineItems.sortOrder));
  }

  async createLineItem(data: InsertEstimateLineItem): Promise<EstimateLineItem> {
    const [item] = await db.insert(estimateLineItems).values(data).returning();
    if (!item) throw new Error('Failed to create line item');
    return item;
  }

  async updateLineItem(id: string, data: Partial<Omit<InsertEstimateLineItem, 'id' | 'estimateId'>>): Promise<EstimateLineItem> {
    const [item] = await db
      .update(estimateLineItems)
      .set(data)
      .where(eq(estimateLineItems.id, id))
      .returning();
    if (!item) throw new NotFoundError(`Line item with ID ${id} not found.`);
    return item;
  }

  async deleteLineItem(id: string): Promise<EstimateLineItem | undefined> {
    const [item] = await db.delete(estimateLineItems).where(eq(estimateLineItems.id, id)).returning();
    return item;
  }

  async bulkCreateLineItems(items: InsertEstimateLineItem[]): Promise<EstimateLineItem[]> {
    if (items.length === 0) return [];
    const createdItems = await db.insert(estimateLineItems).values(items).returning();
    return createdItems;
  }

  async bulkUpdateLineItems(items: Array<Partial<EstimateLineItem> & { id: string }>): Promise<EstimateLineItem[]> {
    if (items.length === 0) return [];
    // Drizzle doesn't have a direct bulk update returning modified rows in one go like some ORMs.
    // We need to run updates in a transaction or individually.
    // For simplicity, running individually. For performance with many items, a transaction with prepared statements is better.
    const updatedItems: EstimateLineItem[] = [];
    for (const item of items) {
      const { id, ...updateData } = item;
      if (id) {
        const [updated] = await db.update(estimateLineItems).set(updateData).where(eq(estimateLineItems.id, id)).returning();
        if (updated) updatedItems.push(updated);
      }
    }
    return updatedItems;
  }
  
  async bulkDeleteLineItems(ids: string[]): Promise<EstimateLineItem[]> {
    if (ids.length === 0) return [];
    const deletedItems = await db.delete(estimateLineItems).where(inArray(estimateLineItems.id, ids)).returning();
    return deletedItems;
  }
  
  async updateLineItemSortOrder(items: Array<{ id: string; sortOrder: number }>): Promise<void> {
    if (items.length === 0) return;
    // Use a transaction to update all sort orders atomically
    await db.transaction(async (tx) => {
      for (const item of items) {
        await tx
          .update(estimateLineItems)
          .set({ sortOrder: item.sortOrder })
          .where(eq(estimateLineItems.id, item.id));
      }
    });
  }


  // --- Estimate Templates ---

  async createEstimateTemplate(data: Omit<InsertEstimateTemplate, 'id' | 'createdAt' | 'updatedAt'>): Promise<EstimateTemplate> {
    const [template] = await db.insert(estimateTemplates).values(data).returning();
    if (!template) throw new Error('Failed to create estimate template');
    return template;
  }

  async updateEstimateTemplate(id: string, data: Partial<Omit<InsertEstimateTemplate, 'id' | 'createdAt' | 'updatedAt'>>): Promise<EstimateTemplate> {
    const [template] = await db
      .update(estimateTemplates)
      .set({ ...data, updatedAt: new Date() })
      .where(eq(estimateTemplates.id, id))
      .returning();
    if (!template) throw new NotFoundError(`Estimate template with ID ${id} not found.`);
    return template;
  }

  async getEstimateTemplateById(id: string): Promise<EstimateTemplate | undefined> {
    const [template] = await db.select().from(estimateTemplates).where(eq(estimateTemplates.id, id));
    return template;
  }

  async getEstimateTemplates(params: {
    page?: number;
    limit?: number;
    search?: string; // Search by name or description
    industryTag?: string;
    visibility?: string;
    sortBy?: keyof EstimateTemplate;
    sortDirection?: 'asc' | 'desc';
  }): Promise<{ data: EstimateTemplate[]; pagination: { total: number; page: number; limit: number; pages: number } }> {
    const {
      page = 1,
      limit = 50,
      search,
      industryTag,
      visibility,
      sortBy = 'createdAt',
      sortDirection = 'desc',
    } = params;

    const offset = (page - 1) * limit;
    const conditions = [];

    if (search) {
      conditions.push(
        or(
          ilike(estimateTemplates.name, `%${search}%`),
          ilike(estimateTemplates.description, `%${search}%`)
        )
      );
    }
    if (industryTag) {
      // Assuming industryTag is stored as JSONB array of strings: '["tag1", "tag2"]'
      conditions.push(sql`${estimateTemplates.industryTag} @> ${JSON.stringify([industryTag])}`);
    }
    if (visibility) {
      conditions.push(eq(estimateTemplates.visibility, visibility));
    }
    
    const whereClause = conditions.length > 0 ? and(...conditions) : undefined;

    const dataQuery = db
      .select()
      .from(estimateTemplates)
      .where(whereClause)
      .orderBy(sortDirection === 'asc' ? asc(estimateTemplates[sortBy]) : desc(estimateTemplates[sortBy]))
      .limit(limit)
      .offset(offset);

    const countQuery = db
      .select({ total: drizzleCount(estimateTemplates.id) })
      .from(estimateTemplates)
      .where(whereClause);

    const [data, totalResult] = await Promise.all([dataQuery, countQuery]);
    const total = totalResult[0].total;

    return {
      data,
      pagination: {
        total,
        page,
        limit,
        pages: Math.ceil(total / limit),
      },
    };
  }

  async deleteEstimateTemplate(id: string): Promise<EstimateTemplate | undefined> {
    const [template] = await db.delete(estimateTemplates).where(eq(estimateTemplates.id, id)).returning();
    return template;
  }

  // --- Estimate Statistics ---
  async getEstimateStats(): Promise<{
    countByStatus: Array<{ status: string; count: number }>;
    totalValueApproved: number;
    averageEstimateValue: number;
  }> {
    const countByStatusQuery = db
      .select({
        status: modernEstimates.status,
        count: sql<number>`count(${modernEstimates.id})`.mapWith(Number),
      })
      .from(modernEstimates)
      .groupBy(modernEstimates.status);

    const totalValueApprovedQuery = db
      .select({
        total: sum(modernEstimates.total).mapWith(Number),
      })
      .from(modernEstimates)
      .where(eq(modernEstimates.status, 'approved'));
      
    const averageEstimateValueQuery = db
      .select({
        avg: sql<number>`avg(${modernEstimates.total})`.mapWith(Number),
      })
      .from(modernEstimates);

    const [statusCounts, approvedTotalResult, avgResult] = await Promise.all([
      countByStatusQuery,
      totalValueApprovedQuery,
      averageEstimateValueQuery,
    ]);
    
    const totalValueApproved = approvedTotalResult[0]?.total || 0;
    const averageEstimateValue = avgResult[0]?.avg || 0;

    return {
      countByStatus: statusCounts,
      totalValueApproved,
      averageEstimateValue,
    };
  }
}

// Singleton instance
export const estimateRepository = new EstimateRepository();
